export const HNdistrictData = [
  {
    district_id: "271",
    district_name: "Huyện Ba Vì",
    province_id: "01",
  },
  {
    district_id: "277",
    district_name: "Huyện Chương Mỹ",
    province_id: "01",
  },
  {
    district_id: "273",
    district_name: "Huyện Đan Phượng",
    province_id: "01",
  },
  {
    district_id: "017",
    district_name: "Huyện Đông Anh",
    province_id: "01",
  },
  {
    district_id: "018",
    district_name: "Huyện Gia Lâm",
    province_id: "01",
  },
  {
    district_id: "274",
    district_name: "Huyện Hoài Đức",
    province_id: "01",
  },
  {
    district_id: "250",
    district_name: "Huyện Mê Linh",
    province_id: "01",
  },
  {
    district_id: "282",
    district_name: "Huyện Mỹ Đức",
    province_id: "01",
  },
  {
    district_id: "280",
    district_name: "Huyện Phú Xuyên",
    province_id: "01",
  },
  {
    district_id: "272",
    district_name: "Huyện Phúc Thọ",
    province_id: "01",
  },
  {
    district_id: "275",
    district_name: "Huyện Quốc Oai",
    province_id: "01",
  },
  {
    district_id: "016",
    district_name: "Huyện Sóc Sơn",
    province_id: "01",
  },
  {
    district_id: "276",
    district_name: "Huyện Thạch Thất",
    province_id: "01",
  },
  {
    district_id: "278",
    district_name: "Huyện Thanh Oai",
    province_id: "01",
  },
  {
    district_id: "020",
    district_name: "Huyện Thanh Trì",
    province_id: "01",
  },
  {
    district_id: "279",
    district_name: "Huyện Thường Tín",
    province_id: "01",
  },
  {
    district_id: "281",
    district_name: "Huyện Ứng Hòa",
    province_id: "01",
  },
  {
    district_id: "001",
    district_name: "Quận Ba Đình",
    district_type: "Quận",
    lat: null,
    lng: null,
    province_id: "01",
  },
  {
    district_id: "021",
    district_name: "Quận Bắc Từ Liêm",
    district_type: "Quận",
    lat: null,
    lng: null,
    province_id: "01",
  },
  {
    district_id: "005",
    district_name: "Quận Cầu Giấy",
    district_type: "Quận",
    lat: null,
    lng: null,
    province_id: "01",
  },
  {
    district_id: "006",
    district_name: "Quận Đống Đa",
    district_type: "Quận",
    lat: null,
    lng: null,
    province_id: "01",
  },
  {
    district_id: "268",
    district_name: "Quận Hà Đông",
    district_type: "Quận",
    lat: null,
    lng: null,
    province_id: "01",
  },
  {
    district_id: "007",
    district_name: "Quận Hai Bà Trưng",
    district_type: "Quận",
    lat: null,
    lng: null,
    province_id: "01",
  },
  {
    district_id: "002",
    district_name: "Quận Hoàn Kiếm",
    district_type: "Quận",
    lat: null,
    lng: null,
    province_id: "01",
  },
  {
    district_id: "008",
    district_name: "Quận Hoàng Mai",
    district_type: "Quận",
    lat: null,
    lng: null,
    province_id: "01",
  },
  {
    district_id: "004",
    district_name: "Quận Long Biên",
    district_type: "Quận",
    lat: null,
    lng: null,
    province_id: "01",
  },
  {
    district_id: "019",
    district_name: "Quận Nam Từ Liêm",
    district_type: "Quận",
    lat: null,
    lng: null,
    province_id: "01",
  },
  {
    district_id: "003",
    district_name: "Quận Tây Hồ",
    district_type: "Quận",
    lat: null,
    lng: null,
    province_id: "01",
  },
  {
    district_id: "009",
    district_name: "Quận Thanh Xuân",
    district_type: "Quận",
    lat: null,
    lng: null,
    province_id: "01",
  },
  {
    district_id: "269",
    district_name: "Thị xã Sơn Tây",
    district_type: "Thị xã",
    lat: null,
    lng: null,
    province_id: "01",
  },
];
